### ISSUE TITLE
Dopo salvataggio primo test con Esito positivo, impossibile eseguire test successivi

### ISSUE THREAD

**Issue by fvlgnn** [italia/spid-saml-check#147]
Dopo aver eseguito il primo test spuntato con esito positivo è impossibile proseguire con gli altri test. Selezionando su _Continua_ alla richiesta _Seleziona se continuare dal report precedente o iniziare un nuovo report..._ e selezionando la pagina _Check response_ viene visualizzato un messaggio di Errore:

```
TypeError: Cannot read property 'nodeType' of undefined
    at Function.PathExpr.getRoot (/spid-saml-check/spid-validator/server/node_modules/xpath/xpath.js:1787:19)
    at Function.PathExpr.applyLocationPath (/spid-saml-check/spid-validator/server/node_modules/xpath/xpath.js:2076:54)
    at PathExpr.evaluate (/spid-saml-check/spid-validator/server/node_modules/xpath/xpath.js:2091:23)
    at XPath.evaluate (/spid-saml-check/spid-validator/server/node_modules/xpath/xpath.js:1317:25)
    at XPathExpression.evaluate (/spid-saml-check/spid-validator/server/node_modules/xpath/xpath.js:4315:26)
    at Object.exports.selectWithResolver (/spid-saml-check/spid-validator/server/node_modules/xpath/xpath.js:4738:26)
    at /spid-saml-check/spid-validator/server/node_modules/xpath/xpath.js:4730:18
    at MetadataParser.getAttributeConsumingService (/spid-saml-check/spid-validator/server/lib/saml-utils.js:197:19)
    at /spid-saml-check/spid-validator/server/api/response.js:59:64
    at Layer.handle [as handle_request] (/spid-saml-check/spid-validator/server/node_modules/express/lib/router/layer.js:95:5)
```

Analizzando la console del browser fallisce il `POST /api/test-response/test-suite-1/2` con messaggio _Failed to load resource: the server responded with a status of 500 (Internal Server Error)_

```
getTestResponse Error

{
    "message": "Request failed with status code 500",
    "name": "Error",
    "stack": "Error: Request failed with status code 500\n    at e.exports (https://fqdn-del-validatore/assets/index.bundle.js:1:132916)\n    at e.exports (https://fqdn-del-validatore/assets/index.bundle.js:1:135454)\n    at XMLHttpRequest.m.onreadystatechange (https://fqdn-del-validatore/assets/index.bundle.js:1:128004)",
    "config": {
        "url": "/api/test-response/test-suite-1/2?apikey=55a95a74a9f5de54898abad98ca75856de98c91c8e99b0ab24495cc5f7e2c4a0",
        "method": "post",
        "data": "{\"suiteid\":\"test-suite-1\",\"caseid\":\"2\",\"params\":[],\"sign_response\":null,\"sign_assertion\":null}",
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json;charset=utf-8"
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1
    }
}
```

E' utilizzata l'ultima versione disponibile alla data odierna su ambiente OpenShift. Lo stesso test è stato eseguito su docker in locale e remoto restituendo lo stesso identico errore.

**Comment by damikael** [comment]
Verificare se il metadata risulta caricato correttamente nella sezione Metadata Download.
Se il metadata non risulta caricato controllare che l'Issuer della Request corrisponda all'EntityID del metadata.
