### ISSUE TITLE
Due esempi due errori

### ISSUE THREAD

**Issue by christiansicari** [italia/spid-saml-check#223]
```
# Executes the last version
docker run -t -i -p 8443:8443 italia/spid-saml-check
```
Ritorna questo errore:
`> spid-validator@1.0.0 start-prod /spid-saml-check/spid-validator
> node server/spid-validator.js

```
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'express'
Require stack:
- /spid-saml-check/spid-validator/server/spid-validator.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/spid-saml-check/spid-validator/server/spid-validator.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/spid-saml-check/spid-validator/server/spid-validator.js' ]
}
```
`

```
# Executes a specific version
docker run -t -i -p 8443:8443 italia/spid-saml-check:v.1.8.2
```
Il server in questo caso è in ascolto della 8080 in realtà, ma anche mappandola si ha empty response

**Comment by gdocalgo** [comment]
Buongiorno a tutti,
anche io ho riscontrato i due problemi segnalati.
Il mio ambiente: SO: kubuntu: 22.04, Docker: 20.10.17

Se invece compilo ed eseguo  l'immagine docker in locale mi ritorna il seguente errore:

`The command '/bin/sh -c cd /spid-saml-check/spid-validator &&     cd client && npm install --silent && cd .. &&     cd server && npm install --silent && cd .. &&     npm run build' returned a non-zero code: 1`
