### ISSUE TITLE
Validator ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by lucavergantini** [italia/spid-saml-check#248]
Eseguo il validator tramite docker, versione 1.9.5.
Registro correttamente il metadato, anche se devo aggirare il bug #247 .

Andando a validare la request, ottengo il seguente errore:
`>>> DATABASE EXCEPTION (saveStore)
"TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined"

>>> DATABASE EXCEPTION (setMetadataValidation)
"TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined"
(node:26) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:330:9)
    at Function.btoa (/spid-saml-check/spid-validator/server/lib/utils.js:182:23)
    at Database.saveStore (/spid-saml-check/spid-validator/server/lib/database.js:101:45)
    at Database.setRequestValidation (/spid-saml-check/spid-validator/server/lib/database.js:442:18)
    at /spid-saml-check/spid-validator/server/api/request.js:127:34
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:26) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)`

Riporto il metadato del mio SP:
`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" 
xmlns:spid="https://spid.gov.it/saml-extensions" ID="_f7ea52f2bc464643a609b642560efb46" 
entityID="http://myspidsp.it"><ds:Signature>
<ds:SignedInfo>
<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
<ds:Reference URI="#_f7ea52f2bc464643a609b642560efb46">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
<ds:DigestValue>Iwb9CNFvcYmQNctYeSbcl6BHFwS3qCBniKA3ObgLDdw=</ds:DigestValue>
</ds:Reference>
</ds:SignedInfo>
<ds:SignatureValue>
Mpo25CIzKDgjyy7vxsNs/ibNvNEeWptQzONTwlpZb7FD0mawppoLuOMxYOdCN6AJOq7xww4SL1OE
Se0VF14YxO7ADETNDyArUjbkjoLZ0FlbWRU16PsbqSJwTmuDCRgmvDv1pBtiWkqUcp4ggRXRg3/g
9pXxbuW8THBQDR927StRMGOuIj+U1kx1floPzqhAgn2NNqm6bzXkPUqnwI9jgqaFxwEjBLjVB1YU
agw/RcI3/2HaDEO/YVxgYNCcbWHnocaJCgah9jhJGSd/K+FKmyTBg6/DtownMnlMoMGL773PsWZW
vFCEJfvt1z8/BdGHMDllV8l1b2B7nLQCHqeFQIIxsq6J8V89wzOh4e7ThKs/W/4IP87BDFfvVeNh
hMhyfLPSKcA+l+KpDH2ze14Zcc+5kZmv5FmdA3TyjJG3u1bcESWA9ig+7zTxQ3fIVn8qC0LINvV8
F1nWnBt8Jxf6i+u09giUO8tOOuxyvwvXWNnn8TRE8RUBv91Weg0fiKWs
</ds:SignatureValue>
<ds:KeyInfo>
<ds:KeyValue>
<ds:RSAKeyValue>
<ds:Modulus>
k+Blf69VLthnifdvm7yw4g03A7GjSFMBjKP4N74vgHnXEt16FMgSBfhnKbR9f44rpf0LIoB9Nyl9
eMerJePFROPBqFPaNOZPdFUjde+QaHYftz/suWiUjCfRndJRAAtU+K/q43spXfjgLXAKJVIS7NlV
EjRHyoG2O2JB45IZqP0XBaepSYRp/mRqIpBdLAsiRdzyp3O/jtZ4Txd86UkiNkvf1bi+JzZ0oKW9
0oO7lzdvps0Xi+gYPl7f2UHSKOCf62iDc9C6o85SglAxbYYasoEav5r3LdnAFao4fb/YIWKIGyCl
4guBvuXrpJ0L4A72fbvg6lBqtQLMI35+sQRAqmYr0e/qlwwTv0gDg8ZH9kqPy9BD+NC7F8Fta8kg
/SuORlkXvDlCNqTPWvhiKUWOMJRyd5sx2qEluXAnqVZH8cfYLssfxqA6AUjqZErWLaYxD8qg5qfu
H8GreznRf04q1P84AijEvQc6YjxosqTvdQ9SLAwd20Ai+EgHBxMAHlEZ
</ds:Modulus>
<ds:Exponent>AQAB</ds:Exponent>
</ds:RSAKeyValue>
</ds:KeyValue>
<ds:X509Data>
<ds:X509Certificate>
MIIGJjCCBI6gAwIBAgIUQBmmnWG0ueosiUedL++nRESzI/8wDQYJKoZIhvcNAQELBQAwgYoxJDAi
BgNVBAoMG0EgQ29tcGFueSBNYWtpbmcgRXZlcnl0aGluZzEQMA4GA1UEAwwHQS5DLk0uRTEdMBsG
A1UEUwwUaHR0cHM6Ly9zcGlkLmFjbWUuaXQxFTATBgNVBGEMDFBBOklULWNfaDUwMTELMAkGA1UE
BhMCSVQxDTALBgNVBAcMBFJvbWEwHhcNMjMwODA3MDgzNzExWhcNMjQwODA2MDgzNzExWjCBijEk
MCIGA1UECgwbQSBDb21wYW55IE1ha2luZyBFdmVyeXRoaW5nMRAwDgYDVQQDDAdBLkMuTS5FMR0w
GwYDVQRTDBRodHRwczovL3NwaWQuYWNtZS5pdDEVMBMGA1UEYQwMUEE6SVQtY19oNTAxMQswCQYD
VQQGEwJJVDENMAsGA1UEBwwEUm9tYTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAJPg
ZX+vVS7YZ4n3b5u8sOINNwOxo0hTAYyj+De+L4B51xLdehTIEgX4Zym0fX+OK6X9CyKAfTcpfXjH
qyXjxUTjwahT2jTmT3RVI3XvkGh2H7c/7LlolIwn0Z3SUQALVPiv6uN7KV344C1wCiVSEuzZVRI0
R8qBtjtiQeOSGaj9FwWnqUmEaf5kaiKQXSwLIkXc8qdzv47WeE8XfOlJIjZL39W4vic2dKClvdKD
u5c3b6bNF4voGD5e39lB0ijgn+tog3PQuqPOUoJQMW2GGrKBGr+a9y3ZwBWqOH2/2CFiiBsgpeIL
gb7l66SdC+AO9n274OpQarUCzCN+frEEQKpmK9Hv6pcME79IA4PGR/ZKj8vQQ/jQuxfBbWvJIP0r
jkZZF7w5Qjakz1r4YilFjjCUcnebMdqhJblwJ6lWR/HH2C7LH8agOgFI6mRK1i2mMQ/KoOan7h/B
q3s50X9OKtT/OAIoxL0HOmI8aLKk73UPUiwMHdtAIvhIBwcTAB5RGQIDAQABo4IBgDCCAXwwCQYD
VR0TBAIwADAOBgNVHQ8BAf8EBAMCBsAwcwYDVR0gBGwwajAfBgMrTBAwGDAWBggrBgEFBQcCAjAK
DAhBZ0lEcm9vdDAgBgQrTBAGMBgwFgYIKwYBBQUHAgIwCgwIYWdJRGNlcnQwJQYGK0wQBAIBMBsw
GQYIKwYBBQUHAgIwDQwLY2VydF9TUF9QdWIwHQYDVR0OBBYEFA/7smxTpI6i2q9fMkxwZrIipH/s
MIHKBgNVHSMEgcIwgb+AFA/7smxTpI6i2q9fMkxwZrIipH/soYGQpIGNMIGKMSQwIgYDVQQKDBtB
IENvbXBhbnkgTWFraW5nIEV2ZXJ5dGhpbmcxEDAOBgNVBAMMB0EuQy5NLkUxHTAbBgNVBFMMFGh0
dHBzOi8vc3BpZC5hY21lLml0MRUwEwYDVQRhDAxQQTpJVC1jX2g1MDExCzAJBgNVBAYTAklUMQ0w
CwYDVQQHDARSb21hghRAGaadYbS56iyJR50v76dERLMj/zANBgkqhkiG9w0BAQsFAAOCAYEAWdKE
tpHODJ9ic0HGCub7yhCq4LB/Y8YUN1rcF+DBUjWDzjJ8lVWXArOYgL1B4tXnDkhFJY8GOi0Cyp2m
CIG4rIE7cTp/NQC+xcpHJu1mMp+IIxrs8Qv2d9dmXnXPIlj7hAcRqNnyRnBiEAwVg7cU7ZRE3RI4
ySBhA3+FIDbNxY5hiRQE5YBaEGwuPfwzrnn0k4V7GH8pGoG+dMA63K7hUiB8OXlTrvHn7Y9aPv4w
1Xn2tIkruhRk4p4Ldaqs1W387L0V5Alqbwi1/1OyErqKDHHCHncer/dWJU9UlnUBjzo/8NJaPMCZ
f/mLTKf8ogtHTOcP0G0tU6FjehxhwqeS8AxzWd1ZtyFsT9V7xx9Hh0cBNBVcXIAOukZcrtDtmXCG
sTska7k0s2ObmGaI8lQuhibQrdx2rg2/jDARAKmJRKQ8GJrNvy7+vbJEdf5c0vBePP8jvO3mM/wU
9UPFX6yxiW2B91ftDluvChjgzfXeUWLX8zzGZGyphyXVYGiTm97m
</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</ds:Signature>
	<md:SPSSODescriptor AuthnRequestsSigned="true" WantAssertionsSigned="true" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
		<md:KeyDescriptor use="signing">
			<ds:KeyInfo>
				<ds:X509Data>
					<ds:X509Certificate>MIIGJjCCBI6gAwIBAgIUQBmmnWG0ueosiUedL++nRESzI/8wDQYJKoZIhvcNAQEL
BQAwgYoxJDAiBgNVBAoMG0EgQ29tcGFueSBNYWtpbmcgRXZlcnl0aGluZzEQMA4G
A1UEAwwHQS5DLk0uRTEdMBsGA1UEUwwUaHR0cHM6Ly9zcGlkLmFjbWUuaXQxFTAT
BgNVBGEMDFBBOklULWNfaDUwMTELMAkGA1UEBhMCSVQxDTALBgNVBAcMBFJvbWEw
HhcNMjMwODA3MDgzNzExWhcNMjQwODA2MDgzNzExWjCBijEkMCIGA1UECgwbQSBD
b21wYW55IE1ha2luZyBFdmVyeXRoaW5nMRAwDgYDVQQDDAdBLkMuTS5FMR0wGwYD
VQRTDBRodHRwczovL3NwaWQuYWNtZS5pdDEVMBMGA1UEYQwMUEE6SVQtY19oNTAx
MQswCQYDVQQGEwJJVDENMAsGA1UEBwwEUm9tYTCCAaIwDQYJKoZIhvcNAQEBBQAD
ggGPADCCAYoCggGBAJPgZX+vVS7YZ4n3b5u8sOINNwOxo0hTAYyj+De+L4B51xLd
ehTIEgX4Zym0fX+OK6X9CyKAfTcpfXjHqyXjxUTjwahT2jTmT3RVI3XvkGh2H7c/
7LlolIwn0Z3SUQALVPiv6uN7KV344C1wCiVSEuzZVRI0R8qBtjtiQeOSGaj9FwWn
qUmEaf5kaiKQXSwLIkXc8qdzv47WeE8XfOlJIjZL39W4vic2dKClvdKDu5c3b6bN
F4voGD5e39lB0ijgn+tog3PQuqPOUoJQMW2GGrKBGr+a9y3ZwBWqOH2/2CFiiBsg
peILgb7l66SdC+AO9n274OpQarUCzCN+frEEQKpmK9Hv6pcME79IA4PGR/ZKj8vQ
Q/jQuxfBbWvJIP0rjkZZF7w5Qjakz1r4YilFjjCUcnebMdqhJblwJ6lWR/HH2C7L
H8agOgFI6mRK1i2mMQ/KoOan7h/Bq3s50X9OKtT/OAIoxL0HOmI8aLKk73UPUiwM
HdtAIvhIBwcTAB5RGQIDAQABo4IBgDCCAXwwCQYDVR0TBAIwADAOBgNVHQ8BAf8E
BAMCBsAwcwYDVR0gBGwwajAfBgMrTBAwGDAWBggrBgEFBQcCAjAKDAhBZ0lEcm9v
dDAgBgQrTBAGMBgwFgYIKwYBBQUHAgIwCgwIYWdJRGNlcnQwJQYGK0wQBAIBMBsw
GQYIKwYBBQUHAgIwDQwLY2VydF9TUF9QdWIwHQYDVR0OBBYEFA/7smxTpI6i2q9f
MkxwZrIipH/sMIHKBgNVHSMEgcIwgb+AFA/7smxTpI6i2q9fMkxwZrIipH/soYGQ
pIGNMIGKMSQwIgYDVQQKDBtBIENvbXBhbnkgTWFraW5nIEV2ZXJ5dGhpbmcxEDAO
BgNVBAMMB0EuQy5NLkUxHTAbBgNVBFMMFGh0dHBzOi8vc3BpZC5hY21lLml0MRUw
EwYDVQRhDAxQQTpJVC1jX2g1MDExCzAJBgNVBAYTAklUMQ0wCwYDVQQHDARSb21h
ghRAGaadYbS56iyJR50v76dERLMj/zANBgkqhkiG9w0BAQsFAAOCAYEAWdKEtpHO
DJ9ic0HGCub7yhCq4LB/Y8YUN1rcF+DBUjWDzjJ8lVWXArOYgL1B4tXnDkhFJY8G
Oi0Cyp2mCIG4rIE7cTp/NQC+xcpHJu1mMp+IIxrs8Qv2d9dmXnXPIlj7hAcRqNny
RnBiEAwVg7cU7ZRE3RI4ySBhA3+FIDbNxY5hiRQE5YBaEGwuPfwzrnn0k4V7GH8p
GoG+dMA63K7hUiB8OXlTrvHn7Y9aPv4w1Xn2tIkruhRk4p4Ldaqs1W387L0V5Alq
bwi1/1OyErqKDHHCHncer/dWJU9UlnUBjzo/8NJaPMCZf/mLTKf8ogtHTOcP0G0t
U6FjehxhwqeS8AxzWd1ZtyFsT9V7xx9Hh0cBNBVcXIAOukZcrtDtmXCGsTska7k0
s2ObmGaI8lQuhibQrdx2rg2/jDARAKmJRKQ8GJrNvy7+vbJEdf5c0vBePP8jvO3m
M/wU9UPFX6yxiW2B91ftDluvChjgzfXeUWLX8zzGZGyphyXVYGiTm97m</ds:X509Certificate>
				</ds:X509Data>
			</ds:KeyInfo>
		</md:KeyDescriptor>
		<md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://192.168.1.67:8080/spidLogout"/>
		<md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://192.168.1.67:8080/spidLogin" index="0" isDefault="true"/>
		<md:AttributeConsumingService index="0">
			<md:ServiceName xml:lang="it">Set Attributi 0</md:ServiceName>
			<md:RequestedAttribute Name="spidCode"/>
			<md:RequestedAttribute Name="name"/>
			<md:RequestedAttribute Name="familyName"/>
			<md:RequestedAttribute Name="placeOfBirth"/>
			<md:RequestedAttribute Name="countyOfBirth"/>
			<md:RequestedAttribute Name="dateOfBirth"/>
			<md:RequestedAttribute Name="gender"/>
			<md:RequestedAttribute Name="companyName"/>
			<md:RequestedAttribute Name="registeredOffice"/>
			<md:RequestedAttribute Name="fiscalNumber"/>
			<md:RequestedAttribute Name="ivaCode"/>
			<md:RequestedAttribute Name="idCard"/>
			<md:RequestedAttribute Name="mobilePhone"/>
			<md:RequestedAttribute Name="email"/>
			<md:RequestedAttribute Name="address"/>
			<md:RequestedAttribute Name="expirationDate"/>
			<md:RequestedAttribute Name="digitalAddress"/>
		</md:AttributeConsumingService>
	</md:SPSSODescriptor>
	<md:Organization>
		<md:OrganizationName xml:lang="it">MySP</md:OrganizationName>
		<md:OrganizationDisplayName xml:lang="it">MySP</md:OrganizationDisplayName>
		<md:OrganizationURL xml:lang="it">https://www.abc.it</md:OrganizationURL>
	</md:Organization>
	<md:ContactPerson contactType="other">
		<md:Extensions>
			<spid:IPACode>bdi_rm</spid:IPACode>
			<spid:VATNumber>IT99999999999</spid:VATNumber>
			<spid:Public/>
		</md:Extensions>
		<md:Company>MySP</md:Company>
		<md:EmailAddress>mysp@aaa.it</md:EmailAddress>
	</md:ContactPerson>
</md:EntityDescriptor>`

E la mia authn request:
`<?xml version="1.0" encoding="UTF-8"?>
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" AssertionConsumerServiceIndex="0" AttributeConsumingServiceIndex="1" Destination="https://localhost:8443/samlsso" ForceAuthn="true" ID="_f7ea52f2bc464643a609b642560efb46" IssueInstant="2023-08-09T09:43:37.357Z" Version="2.0">
    <saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" 
	NameQualifier="http://myspidsp.it"/>
    <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:SignedInfo>
            <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
            <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
            <ds:Reference URI="#_f7ea52f2bc464643a609b642560efb46">
                <ds:Transforms>
                    <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                    <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                </ds:Transforms>
                <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
                <ds:DigestValue>
                    Y2ZLs4+78wbm+wz0jOZqOxS/3IA=
                </ds:DigestValue>
            </ds:Reference>
        </ds:SignedInfo>
        <ds:SignatureValue>
            dvSe4wAYqx6yu0YUGG7iNdiZhCyKI51KnUlKmTDr/WjszZOlrLeIvEaCJ6d3aQ51aVakhmADQfpWnXKLyvwEh5KUxCpa46wqb+A2FyMF40LYGEMFsKLbrFuQQ63HJzzTc4s4db2hrw3xJ7u0s3/39dCvHJCPK7PSycClyIKPxTnpfiWP4n1Qdn3lgqWsVxXxLuzzj4AVDR/uVBl6rlyxb8oxe75MfR4nZ0p+fY3GSDECtdwQDXxeLwM6M9lRatktX7OcCjkk0I6N2zfMEQdASMwP5YTdQtrRgIMgzO52v/epZ6a2gUlXEkLJDWKYW0C8WdsMarRIrdb6oES2oj0Sp4Gs93MYj5VsP6xSd4B8AgswOJBoZAR430Xtu8eWKUi9AOZi727EYMqEJQX9Tl2LZaWBnWqRuhUexrGewKeDJsx9IGsSDgTCWHcgHRLSbcr8Lk4gdSO7LBcsXguUbtTjWHjiP55n49u+VqzL5ps5VPubrPB0iTllizl1EJAFJ0Ft
        </ds:SignatureValue>
        <ds:KeyInfo>
            <ds:X509Data>
                <ds:X509Certificate>
                    MIIGJjCCBI6gAwIBAgIUQBmmnWG0ueosiUedL++nRESzI/8wDQYJKoZIhvcNAQELBQAwgYoxJDAi
BgNVBAoMG0EgQ29tcGFueSBNYWtpbmcgRXZlcnl0aGluZzEQMA4GA1UEAwwHQS5DLk0uRTEdMBsG
A1UEUwwUaHR0cHM6Ly9zcGlkLmFjbWUuaXQxFTATBgNVBGEMDFBBOklULWNfaDUwMTELMAkGA1UE
BhMCSVQxDTALBgNVBAcMBFJvbWEwHhcNMjMwODA3MDgzNzExWhcNMjQwODA2MDgzNzExWjCBijEk
MCIGA1UECgwbQSBDb21wYW55IE1ha2luZyBFdmVyeXRoaW5nMRAwDgYDVQQDDAdBLkMuTS5FMR0w
GwYDVQRTDBRodHRwczovL3NwaWQuYWNtZS5pdDEVMBMGA1UEYQwMUEE6SVQtY19oNTAxMQswCQYD
VQQGEwJJVDENMAsGA1UEBwwEUm9tYTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAJPg
ZX+vVS7YZ4n3b5u8sOINNwOxo0hTAYyj+De+L4B51xLdehTIEgX4Zym0fX+OK6X9CyKAfTcpfXjH
qyXjxUTjwahT2jTmT3RVI3XvkGh2H7c/7LlolIwn0Z3SUQALVPiv6uN7KV344C1wCiVSEuzZVRI0
R8qBtjtiQeOSGaj9FwWnqUmEaf5kaiKQXSwLIkXc8qdzv47WeE8XfOlJIjZL39W4vic2dKClvdKD
u5c3b6bNF4voGD5e39lB0ijgn+tog3PQuqPOUoJQMW2GGrKBGr+a9y3ZwBWqOH2/2CFiiBsgpeIL
gb7l66SdC+AO9n274OpQarUCzCN+frEEQKpmK9Hv6pcME79IA4PGR/ZKj8vQQ/jQuxfBbWvJIP0r
jkZZF7w5Qjakz1r4YilFjjCUcnebMdqhJblwJ6lWR/HH2C7LH8agOgFI6mRK1i2mMQ/KoOan7h/B
q3s50X9OKtT/OAIoxL0HOmI8aLKk73UPUiwMHdtAIvhIBwcTAB5RGQIDAQABo4IBgDCCAXwwCQYD
VR0TBAIwADAOBgNVHQ8BAf8EBAMCBsAwcwYDVR0gBGwwajAfBgMrTBAwGDAWBggrBgEFBQcCAjAK
DAhBZ0lEcm9vdDAgBgQrTBAGMBgwFgYIKwYBBQUHAgIwCgwIYWdJRGNlcnQwJQYGK0wQBAIBMBsw
GQYIKwYBBQUHAgIwDQwLY2VydF9TUF9QdWIwHQYDVR0OBBYEFA/7smxTpI6i2q9fMkxwZrIipH/s
MIHKBgNVHSMEgcIwgb+AFA/7smxTpI6i2q9fMkxwZrIipH/soYGQpIGNMIGKMSQwIgYDVQQKDBtB
IENvbXBhbnkgTWFraW5nIEV2ZXJ5dGhpbmcxEDAOBgNVBAMMB0EuQy5NLkUxHTAbBgNVBFMMFGh0
dHBzOi8vc3BpZC5hY21lLml0MRUwEwYDVQRhDAxQQTpJVC1jX2g1MDExCzAJBgNVBAYTAklUMQ0w
CwYDVQQHDARSb21hghRAGaadYbS56iyJR50v76dERLMj/zANBgkqhkiG9w0BAQsFAAOCAYEAWdKE
tpHODJ9ic0HGCub7yhCq4LB/Y8YUN1rcF+DBUjWDzjJ8lVWXArOYgL1B4tXnDkhFJY8GOi0Cyp2m
CIG4rIE7cTp/NQC+xcpHJu1mMp+IIxrs8Qv2d9dmXnXPIlj7hAcRqNnyRnBiEAwVg7cU7ZRE3RI4
ySBhA3+FIDbNxY5hiRQE5YBaEGwuPfwzrnn0k4V7GH8pGoG+dMA63K7hUiB8OXlTrvHn7Y9aPv4w
1Xn2tIkruhRk4p4Ldaqs1W387L0V5Alqbwi1/1OyErqKDHHCHncer/dWJU9UlnUBjzo/8NJaPMCZ
f/mLTKf8ogtHTOcP0G0tU6FjehxhwqeS8AxzWd1ZtyFsT9V7xx9Hh0cBNBVcXIAOukZcrtDtmXCG
sTska7k0s2ObmGaI8lQuhibQrdx2rg2/jDARAKmJRKQ8GJrNvy7+vbJEdf5c0vBePP8jvO3mM/wU
9UPFX6yxiW2B91ftDluvChjgzfXeUWLX8zzGZGyphyXVYGiTm97m
                </ds:X509Certificate>
            </ds:X509Data>
        </ds:KeyInfo>
    </ds:Signature>
    <saml2p:NameIDPolicy xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"/>
    <saml2p:RequestedAuthnContext xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" Comparison="exact">
        <saml:AuthnContextClassRef xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">
            https://www.spid.gov.it/SpidL2
        </saml:AuthnContextClassRef>
    </saml2p:RequestedAuthnContext>
</samlp:AuthnRequest>`

**Comment by lucavergantini** [comment]
Scusate, errore mio

**Comment by lucavergantini** [comment]
Errore mio, chiudo
