### ISSUE TITLE
Errore durante startup versione 1.10.2 (ReferenceError: primordials)

### ISSUE THREAD

**Issue by pselvini** [italia/spid-saml-check#253]
Ciao,
dopo aver effettuato la build del container versione 1.10.2, allo startup si ottiene questo log

```
spid-saml-check  | >>> DATABASE : QUERY
spid-saml-check  |
spid-saml-check  | "                 CREATE TABLE log (                     timestamp   DATETIME,                     type        STRING,                       text        STRING (1024)                 );                 CREATE TABLE store (                     user                        STRING,                     organization                INTEGER,                     entity_id                   STRING,                     external_code               STRING UNIQUE,                     timestamp                   DATETIME,                     type                        STRING,                     store                       TEXT,                     PRIMARY KEY (user, entity_id)                     );             "
spid-saml-check  | fs.js:36
spid-saml-check  | } = primordials;
spid-saml-check  |     ^
spid-saml-check  |
spid-saml-check  | ReferenceError: primordials is not defined
spid-saml-check  |     at fs.js:36:5
spid-saml-check  |     at req_ (/spid-saml-check/spid-validator/server/node_modules/natives/index.js:143:24)
spid-saml-check  |     at Object.req [as require] (/spid-saml-check/spid-validator/server/node_modules/natives/index.js:55:10)
spid-saml-check  |     at Object.<anonymous> (/spid-saml-check/spid-validator/server/node_modules/fstream/node_modules/graceful-fs/fs.js:1:37)
spid-saml-check  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
spid-saml-check  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
spid-saml-check  |     at Module.load (internal/modules/cjs/loader.js:863:32)
spid-saml-check  |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
spid-saml-check  |     at Module.require (internal/modules/cjs/loader.js:887:19)
spid-saml-check  |     at require (internal/modules/cjs/helpers.js:74:18)
```

**Comment by damikael** [comment]
La versione [1.10.3](https://github.com/italia/spid-saml-check/releases/tag/v.1.10.3) risolve il problema.
