### ISSUE TITLE
Errore in fase di single logout

### ISSUE THREAD

**Issue by fmartelli** [italia/spid-saml-check#59]
Invocando il single logout nei log viene segnalata la seguente eccezione.
E' un problema di codice o è un problema della richiesta?

<pre>
TypeError: Cannot read property 'request' of undefined
    at /spid-saml-check/spid-validator/server/spid-validator.js:257:24
    at Layer.handle [as handle_request] (/spid-saml-check/spid-validator/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/spid-saml-check/spid-validator/server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/spid-saml-check/spid-validator/server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/spid-saml-check/spid-validator/server/node_modules/express/lib/router/layer.js:95:5)
    at /spid-saml-check/spid-validator/server/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/spid-saml-check/spid-validator/server/node_modules/express/lib/router/index.js:335:12)
    at next (/spid-saml-check/spid-validator/server/node_modules/express/lib/router/index.js:275:10)
    at app.use (/spid-saml-check/spid-validator/server/spid-validator.js:77:5)
    at Layer.handle [as handle_request] (/spid-saml-check/spid-validator/server/node_modules/express/lib/router/layer.js:95:5)
</pre>

**Comment by damikael** [comment]
https://github.com/italia/spid-saml-check/pull/60 fix
